spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
feign:
  autoconfiguration:
    jackson:
      enabled: true

keycloak:
  auth-server-url: http://host.docker.internal:8080/auth
  realm: gate
  resource: gate
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username
  verify-token-audience: true